version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www
    networks:
      - app-network
    ports:
      - 10000:10000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: backportfolio_app
      DB_USERNAME: root
      DB_PASSWORD: root
      PORT: 10000  # Imposta la variabile PORT a 10000
  db:
    image: mysql:5.7
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backportfolio_app
    ports:
      - 3306:3306

networks:
  app-network:
    driver: bridge
